import type { Job, TestQuestion, Application } from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Solutions",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120,000 - $160,000",
    description:
      "We are seeking an experienced Frontend Developer to join our growing team and help build the next generation of web applications.",
    requirements: [
      "5+ years of experience with React and TypeScript",
      "Strong understanding of modern CSS and responsive design",
      "Experience with state management libraries (Redux, Zustand)",
      "Excellent problem-solving skills",
      "Bachelor's degree in Computer Science or related field",
    ],
    responsibilities: [
      "Develop and maintain high-quality web applications",
      "Collaborate with designers and backend developers",
      "Write clean, maintainable, and testable code",
      "Participate in code reviews and technical discussions",
      "Mentor junior developers",
    ],
    postedDate: "2024-01-15",
    department: "Engineering",
    experience: "5+ years",
  },
  {
    id: "2",
    title: "Product Manager",
    company: "InnovateLabs",
    location: "New York, NY",
    type: "Full-time",
    salary: "$130,000 - $170,000",
    description:
      "Join our product team to drive innovation and deliver exceptional user experiences for our enterprise customers.",
    requirements: [
      "3+ years of product management experience",
      "Strong analytical and problem-solving skills",
      "Experience with Agile methodologies",
      "Excellent communication skills",
      "MBA or relevant degree preferred",
    ],
    responsibilities: [
      "Define product vision and roadmap",
      "Work closely with engineering and design teams",
      "Conduct user research and analyze metrics",
      "Prioritize features based on business impact",
      "Present to stakeholders and executives",
    ],
    postedDate: "2024-01-18",
    department: "Product",
    experience: "3+ years",
  },
  {
    id: "3",
    title: "UX/UI Designer",
    company: "DesignFirst Studio",
    location: "Remote",
    type: "Remote",
    salary: "$90,000 - $130,000",
    description:
      "Create beautiful and intuitive user interfaces for web and mobile applications used by millions of users worldwide.",
    requirements: [
      "3+ years of UX/UI design experience",
      "Proficiency in Figma and Adobe Creative Suite",
      "Strong portfolio demonstrating design skills",
      "Understanding of user-centered design principles",
      "Experience with design systems",
    ],
    responsibilities: [
      "Design user interfaces for web and mobile",
      "Create wireframes, prototypes, and mockups",
      "Conduct user research and usability testing",
      "Collaborate with product and engineering teams",
      "Maintain and evolve design system",
    ],
    postedDate: "2024-01-20",
    department: "Design",
    experience: "3+ years",
  },
  {
    id: "4",
    title: "Data Scientist",
    company: "DataDriven Analytics",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$140,000 - $180,000",
    description: "Help us unlock insights from data and build machine learning models that drive business decisions.",
    requirements: [
      "Master's or PhD in Computer Science, Statistics, or related field",
      "Strong programming skills in Python and R",
      "Experience with ML frameworks (TensorFlow, PyTorch)",
      "Solid understanding of statistics and algorithms",
      "Experience with big data technologies",
    ],
    responsibilities: [
      "Develop and deploy machine learning models",
      "Analyze large datasets to extract insights",
      "Collaborate with stakeholders to solve business problems",
      "Present findings to technical and non-technical audiences",
      "Stay current with latest ML/AI research",
    ],
    postedDate: "2024-01-22",
    department: "Data Science",
    experience: "4+ years",
  },
  {
    id: "5",
    title: "Marketing Manager",
    company: "GrowthHub",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$100,000 - $140,000",
    description: "Lead our marketing efforts and help scale our B2B SaaS platform to new heights.",
    requirements: [
      "5+ years of B2B marketing experience",
      "Experience with digital marketing and SEO",
      "Strong understanding of marketing analytics",
      "Excellent written and verbal communication",
      "Experience managing marketing teams",
    ],
    responsibilities: [
      "Develop and execute marketing strategies",
      "Manage content creation and campaigns",
      "Analyze marketing metrics and ROI",
      "Coordinate with sales and product teams",
      "Manage marketing budget and resources",
    ],
    postedDate: "2024-01-25",
    department: "Marketing",
    experience: "5+ years",
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "CloudScale Systems",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$130,000 - $170,000",
    description:
      "Build and maintain our cloud infrastructure to support millions of users with high availability and performance.",
    requirements: [
      "4+ years of DevOps experience",
      "Strong knowledge of AWS, Docker, and Kubernetes",
      "Experience with CI/CD pipelines",
      "Proficiency in scripting (Python, Bash)",
      "Understanding of security best practices",
    ],
    responsibilities: [
      "Design and maintain cloud infrastructure",
      "Implement monitoring and alerting systems",
      "Automate deployment processes",
      "Ensure system security and compliance",
      "Troubleshoot production issues",
    ],
    postedDate: "2024-01-28",
    department: "Engineering",
    experience: "4+ years",
  },
]

export const mockTestQuestions: Record<string, TestQuestion[]> = {
  "1": [
    {
      id: "1",
      question: "What is the main purpose of React Hooks?",
      options: [
        "To style components",
        "To enable state and lifecycle features in functional components",
        "To connect to databases",
        "To handle routing",
      ],
      correctAnswer: 1,
    },
    {
      id: "2",
      question: "Which CSS property is used to create a flexbox layout?",
      options: ["display: block", "display: grid", "display: flex", "display: inline"],
      correctAnswer: 2,
    },
    {
      id: "3",
      question: "What does TypeScript add to JavaScript?",
      options: ["Better performance", "Static typing", "New runtime features", "Automatic testing"],
      correctAnswer: 1,
    },
  ],
  "2": [
    {
      id: "1",
      question: "What is the primary responsibility of a Product Manager?",
      options: ["Writing code", "Designing interfaces", "Defining product vision and strategy", "Managing finances"],
      correctAnswer: 2,
    },
    {
      id: "2",
      question: "Which framework is commonly used in Agile product management?",
      options: ["Waterfall", "Scrum", "Six Sigma", "PRINCE2"],
      correctAnswer: 1,
    },
  ],
  "3": [
    {
      id: "1",
      question: "What does UX stand for?",
      options: ["User Experience", "Universal Export", "User Extension", "Unique Expression"],
      correctAnswer: 0,
    },
    {
      id: "2",
      question: "Which tool is primarily used for UI design and prototyping?",
      options: ["Visual Studio Code", "Figma", "Docker", "Jenkins"],
      correctAnswer: 1,
    },
  ],
}

export const mockApplications: Application[] = [
  {
    id: "1",
    jobId: "1",
    jobTitle: "Senior Frontend Developer",
    candidateName: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    resume: "sarah-johnson-resume.pdf",
    coverLetter: "I am excited to apply for the Senior Frontend Developer position...",
    testScore: 85,
    status: "interview",
    appliedDate: "2024-01-20",
  },
  {
    id: "2",
    jobId: "1",
    jobTitle: "Senior Frontend Developer",
    candidateName: "Michael Chen",
    email: "michael.chen@email.com",
    phone: "+1 (555) 234-5678",
    resume: "michael-chen-resume.pdf",
    coverLetter: "With over 6 years of React experience...",
    testScore: 92,
    status: "reviewing",
    appliedDate: "2024-01-22",
  },
  {
    id: "3",
    jobId: "2",
    jobTitle: "Product Manager",
    candidateName: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    phone: "+1 (555) 345-6789",
    resume: "emily-rodriguez-resume.pdf",
    coverLetter: "As a product manager with 4 years of experience...",
    testScore: 78,
    status: "pending",
    appliedDate: "2024-01-25",
  },
  {
    id: "4",
    jobId: "3",
    jobTitle: "UX/UI Designer",
    candidateName: "David Park",
    email: "david.park@email.com",
    phone: "+1 (555) 456-7890",
    resume: "david-park-resume.pdf",
    coverLetter: "I have a passion for creating intuitive user experiences...",
    status: "accepted",
    appliedDate: "2024-01-26",
  },
]
